on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/link-issues.md

      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"
          comment: false
        continue-on-error: true

      - name: Get the output
        run: echo "Linked issues - ${{ steps.check-linked-issues.outputs.linked_issues_count }} found."

      - name: Create comment from markdown file
        if: always() && (steps.check-linked-issues.outcome == 'failure')
        uses: GrantBirki/comment@v2.0.10
        with:
          file: .github/workflows/link-issues.md
