on: workflow_dispatch

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/link-issues.md


      # - name: Set friendly reminder
      #   id: msg
      #   uses: juliangruber/read-file-action@v1
      #   with:
      #     path: .github/workflows/link-issues.md

      # - name: display string
      #   run: |
      #     echo "The string is: ${{ steps.msg.outputs.content }}"

      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"
          comment: false

      # OPTIONAL: Use the output from the `check-linked-issues` step
      - name: Get the output
        run: echo "Linked issues - ${{ steps.check-linked-issues.outputs.linked_issues_count }} found."

      - name: Create comment from markdown file
        if: steps.check-linked-issues.outputs.linked_issues_count < 1
        uses: GrantBirki/comment@v2.0.10
        with:
          file: demo/plain-sample.md